### ISSUE TITLE
sample运行报错

### ISSUE THREAD

**Issue by EndSmile** [anruence/enode#121]
`java ... org.enodeframework.samples.commandhandles.CommandApplication`
报错：
```
Caused by: java.lang.ClassNotFoundException: io.vertx.mysqlclient.MySQLPool
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 25 common frames omitted
```

而且这个加了`encode-mysql`的依赖后，容器的bean初始化就开始报错

**Comment by anruence** [comment]
新的版本升级了vertx4.0，同时使用了vertx-mysql的client，sample项目还没有完全适配过去

**Comment by anruence** [comment]
最新版本代码samples代码启动运行测试通过
